name: Build and Publish Docker Image to gatewayfm internal registry

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to build from (e.g. develop or main)"
        required: true
        type: string
        default: develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gatewayfm/ethereum-validators-monitoring:${{ inputs.branch }}
            gatewayfm/ethereum-validators-monitoring:latest
